@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor LOGIC_COLOR_T4
skinparam classBackgroundColor LOGIC_COLOR

Class "{abstract}\nCommand" as Command
Class PurchaseCommand
Class AddStaffCommand
Class CustomerAddCommand

package "Parser classes"{
Class "<<interface>>\nParser" as Parser
Class CafeConnectParser
Class PurchaseCommandParser
Class AddStaffCommandParser
Class CustomerAddCommandParser
Class CliSyntax
Class ParserUtil
Class ArgumentMultimap
Class ArgumentTokenizer
Class Prefix
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> CafeConnectParser

CafeConnectParser .down.> PurchaseCommandParser: <<create>>
CafeConnectParser .down.> AddStaffCommandParser: <<create>>
CafeConnectParser .down.> CustomerAddCommandParser: <<create>>

PurchaseCommandParser ..> PurchaseCommand : <<create>>
AddStaffCommandParser ..> AddStaffCommand : <<create>>
CustomerAddCommandParser ..> CustomerAddCommand : <<create>>
CafeConnectParser ..> Command : <<use>>

PurchaseCommandParser .up.|> Parser
AddStaffCommandParser .up.|> Parser
CustomerAddCommandParser .up.|> Parser

PurchaseCommandParser ..> ArgumentMultimap
PurchaseCommandParser ..> ArgumentTokenizer
ArgumentTokenizer .left.> ArgumentMultimap
PurchaseCommandParser ..> CliSyntax
CliSyntax ..> Prefix
PurchaseCommandParser ..> ParserUtil
ParserUtil .down.> Prefix
ArgumentTokenizer .down.> Prefix
PurchaseCommand -up-|> Command
AddStaffCommand -up-|> Command
CustomerAddCommand -up-|> Command
@enduml