@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor UI_COLOR_T4
skinparam classBackgroundColor UI_COLOR

package UI <<Rectangle>>{
Class "<<interface>>\nUi" as Ui
Class "{abstract}\nUiPart" as UiPart
Class UiManager
Class MainWindow
Class HelpWindow
Class ResultDisplay
Class CommandBox
Class StatusBarFooter
Class CustomerListPanel
Class CustomerCard
Class StaffListPanel
Class StaffCard
Class DrinkListPanel
Class DrinkCard
Class ChartWindow
}

package Model <<Rectangle>> {
Class HiddenModel #FFFFFF
}

package Logic <<Rectangle>> {
Class HiddenLogic #FFFFFF
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Ui

UiManager .left.|> Ui
UiManager -down-> "1" MainWindow
MainWindow *-down-> "1" CommandBox
MainWindow *-down-> "1" ResultDisplay
MainWindow *-down-> "1" StatusBarFooter
MainWindow *-down-> "1" CustomerListPanel
MainWindow *-down-> "1" StaffListPanel
MainWindow *-down-> "0..1" DrinkListPanel
MainWindow --> "0..1" HelpWindow
MainWindow --> "0..1" ChartWindow

CustomerListPanel -down-> "*" CustomerCard
StaffListPanel -down-> "*" StaffCard
DrinkListPanel -down-> "*" DrinkCard

MainWindow -left-|> UiPart

ResultDisplay --|> UiPart
CommandBox --|> UiPart
CustomerListPanel --|> UiPart
CustomerCard --|> UiPart
StaffListPanel --|> UiPart
StaffCard --|> UiPart
DrinkListPanel --|> UiPart
DrinkCard --|> UiPart
StatusBarFooter --|> UiPart
HelpWindow --|> UiPart
ChartWindow --|> UiPart

CustomerCard ..> Model
StaffCard ..> Model
DrinkCard ..> Model
UiManager -right-> Logic
MainWindow -left-> Logic

CustomerListPanel -[hidden]left- StaffListPanel
StaffListPanel -[hidden]left- DrinkListPanel
DrinkListPanel -[hidden]left- HelpWindow
HelpWindow -[hidden]left- CommandBox
CommandBox -[hidden]left- ResultDisplay
ResultDisplay -[hidden]left- StatusBarFooter

MainWindow -[hidden]-|> UiPart
@enduml
